name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all tags and branches

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag and create new one
        id: tag_version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null)
          if [ -z "$latest_tag" ]; then
            new_tag="v0.0.1"
          else
            # Increment patch version
            new_tag=$(echo "$latest_tag" | awk -F. -v OFS=. '{$NF = $NF + 1;} 1')
          fi
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "new_tag is $new_tag"

      - name: Create and push new tag
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
